### ISSUE TITLE
User Guide Docs

### ISSUE THREAD

**Issue by trishnaguha** [ansible/ansible-dev-tools#44]
**User Guide will have two sections:**

- links to tool docs etc. Link to the ecosystem docs and each repo
- Common operations using 2 or more tools (cross tools)

Cross tool Common operations are described in the task list.

```[tasklist]
### Tasks
- [x] [Building a new collection](https://github.com/ansible/ansible-dev-tools/issues/46)
- [x] [Testing a user-facing role within a collection](https://github.com/ansible/ansible-dev-tools/issues/47)
- [x] [Ensuring content best practices](https://github.com/ansible/ansible-dev-tools/issues/48)
- [x] [Set up CI](https://github.com/ansible/ansible-dev-tools/issues/49)
- [x] [Publishing a collection](https://github.com/ansible/ansible-dev-tools/issues/50)
```

**Comment by KB-perByte** [comment]
All the docs related to Github action work are - 
- Usage doc : https://github.com/ansible/ansible-github-actions/blob/main/docs/usage.md
- Release doc : https://github.com/ansible/ansible-github-actions/blob/main/docs/release.md
- CI doc : https://github.com/ansible/ansible-github-actions/blob/main/docs/ci.md
Regards

**Comment by ssbarnea** [comment]
Closing as I see all included task as checked.
